EISG20240905.AppWebMVC/Models/ErrorViewModel.cs
namespace EISG20240905.AppWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EISG20240905.AppWebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using EISG20240905.AppWebMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EISG20240905.AppWebMVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

EISG20240905.AppWebMVC/Controllers/ProductEISGController.cs
using EISG20240905.DTOs.ProductEISGDTOs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static System.Net.WebRequestMethods;

namespace EISG20240905.AppWebMVC.Controllers
{
	public class ProductEISGController : Controller
	{
		private readonly HttpClient _httpClientEISG20240905API;

		// Constructor que recibe una instancia de IHttpClientFactory para crear el cliente HTTP
		public ProductEISGController(IHttpClientFactory httpClientFactory)
		{
			_httpClientEISG20240905API = httpClientFactory.CreateClient("EISG20240905API");
		}

		// Método para mostrar la lista de productos
		public async Task<ActionResult> Index(SearchQueryProductEISGDTO searchQueryProductEISGDTO, int CountRow = 0)
		{
			// Configurar valores por defecto
			if (searchQueryProductEISGDTO.SendRowCount == 0)
				searchQueryProductEISGDTO.SendRowCount = 2;
			if (searchQueryProductEISGDTO.Take == 0)
				searchQueryProductEISGDTO.Take = 10;

			var result = new SearchResultProductEISGDTO();

			// Hacer solicitud HTTP POST
			var response = await _httpClientEISG20240905API.PostAsJsonAsync("/product/search", searchQueryProductEISGDTO);

			if (response.IsSuccessStatusCode)
				result = await response.Content.ReadFromJsonAsync<SearchResultProductEISGDTO>();

			// Si result es nulo, inicializar un nuevo objeto
			result = result ?? new SearchResultProductEISGDTO();
			result.Data = result.Data ?? new List<SearchResultProductEISGDTO.ProductEISGDTO>(); // Verifica que Data no sea nulo

			// Configurar valores para la vista
			if (result.CountRow == 0 && searchQueryProductEISGDTO.SendRowCount == 1)
				result.CountRow = CountRow;

			ViewBag.CountRow = result.CountRow;
			searchQueryProductEISGDTO.SendRowCount = 0;
			ViewBag.SearchQuery = searchQueryProductEISGDTO;

			return View(result);
		}

		// Método para mostrar los detalles de un prducto
		public async Task<ActionResult> Details(int id)
		{
			var result = new GetIdResultProductEISGDTO();

			// Realizar una solicitud HTTP GET para obtener los detalles del cliente por ID
			var response = await _httpClientEISG20240905API.GetAsync("/product/" + id);

			if (response.IsSuccessStatusCode)
				result = await response.Content.ReadFromJsonAsync<GetIdResultProductEISGDTO>();

			return View(result ?? new GetIdResultProductEISGDTO());
		}

		// GET: ProductEISGController/Create
		// Método para mostrar el formulario de creación de un producto
		public ActionResult Create()
		{
			return View();
		}

		// POST: ProductEISGController/Create
		// Método para procesar la creación de un producto
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(CreateProductEISGDTO createProductEISGDTO)
		{

			try
			{
				//Realizar una solicitud HTTP POST para crear un nuevo producto
				var response = await _httpClientEISG20240905API.PostAsJsonAsync("/product", createProductEISGDTO);

				if (response.IsSuccessStatusCode)
				{
					return RedirectToAction(nameof(Index));
				}

				ViewBag.Error = "Error al intentar guardar el registro";
				return View();
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				return View();
			}
		}

		// Método para mostrar el formulario de edición de un producto
		// GET: ProductEISGController/Edit/5
		public async Task<ActionResult> Edit(int id)
		{
			var result = new GetIdResultProductEISGDTO();
			var response = await _httpClientEISG20240905API.GetAsync("/product/" + id);

			if (response.IsSuccessStatusCode)
				result = await response.Content.ReadFromJsonAsync<GetIdResultProductEISGDTO>();

			return View(new EditProdcutEISGDTO(result ?? new GetIdResultProductEISGDTO()));
		}

		// POST: ProductEISGController/Edit/5

		// Método para procesar la edición de un producto
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(int id, EditProdcutEISGDTO editProdcutEISGDTO)
		{
			try
			{ // Realizar una solicitud HTTP PUT para editar el producto
				var response = await _httpClientEISG20240905API.PutAsJsonAsync("/product", editProdcutEISGDTO);

				if (response.IsSuccessStatusCode)
				{
					return RedirectToAction(nameof(Index));
				}

				ViewBag.Error = "Error al intentar editar el registro";
				return View();
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				return View();
			}

		}

		// GET: ProductEISGController/Delete/5
		// Método para mostrar la página de confirmación de eliminación de un producto
		public async Task<ActionResult> Delete(int id)
		{
			var result = new GetIdResultProductEISGDTO();
			var response = await _httpClientEISG20240905API.GetAsync("/product/" + id);

			if (response.IsSuccessStatusCode)
				result = await response.Content.ReadFromJsonAsync<GetIdResultProductEISGDTO>();

			return View(result ?? new GetIdResultProductEISGDTO());
		}

		// POST: ProductEISGController/Delete/5
		// Método para procesar la eliminación de un producto
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(int id, GetIdResultProductEISGDTO getIdResultProductEISGDTOa)
		{
			try
			{
				// Realizar una solicitud HTTP DELETE para eliminar el cliente por ID
				var response = await _httpClientEISG20240905API.DeleteAsync("/product/" + id);

				if (response.IsSuccessStatusCode)
				{
					return RedirectToAction(nameof(Index));
				}

				ViewBag.Error = "Error al intentar eliminar el registro";
				return View(getIdResultProductEISGDTOa);
			}
			catch (Exception ex)
			{
				ViewBag.Error = ex.Message;
				return View(getIdResultProductEISGDTOa);
			}
		}
	}
}

EISG20240905.AppWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
</div>

EISG20240905.AppWebMVC/Views/ProductEISG/Create.cshtml
@model EISG20240905.DTOs.ProductEISGDTOs.CreateProductEISGDTO

@{
	ViewData["Title"] = "Create";
}
<div class="row" style="margin-top:70px;">
	<div class="row">
		<form asp-action="Create" method="post" class="card">
			<div class="card-header row">
				<h1 class="card-text col-md-12">Crear Producto</h1>
			</div>
			<div class="card-body row">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group col-md-6">

					<label asp-for="NombreEISG" class="control-label">Nombre<span style="color:red;">*</span></label>
					<input asp-for="NombreEISG" class="form-control" />
					<span asp-validation-for="NombreEISG" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label asp-for="Precio" class="control-label">Precio <span style="color:red;">*</span></label>
					<input asp-for="Precio" type="number" class="form-control" />
					<span asp-validation-for="Precio" class="text-danger"></span>
				</div>
				<div class="form-group col-md-12">
					<label asp-for="DescripcionEISG" class="control-label"></label>
					<textarea asp-for="DescripcionEISG" class="form-control"></textarea>
					<span asp-validation-for="DescripcionEISG" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6" style="margin-top:10px;">
					<input type="submit" value="Guardar" class="btn btn-primary" style="width:100%;" />
				</div>
				<div class="form-group col-md-6" style="margin-top:10px;">
					<a asp-action="Index" class="btn btn-secondary" style="width:100%;">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

EISG20240905.AppWebMVC/Views/ProductEISG/Delete.cshtml
@model EISG20240905.DTOs.ProductEISGDTOs.GetIdResultProductEISGDTO

@{
	ViewData["Title"] = "Delete";
}

<div class="row" style="margin-top:70px;">
	<div class="row">
		<form asp-action="Delete" class="card">
			<div class="card-header row">
				<h1 class="card-text col-md-12">Eliminar Producto</h1>
			</div>
			<div class="card-body row">
				<div class="form-group col-md-6">
					<label asp-for="NombreEISG" class="control-label">Nombre</label>
					<input asp-for="NombreEISG" disabled class="form-control" />
					<span asp-validation-for="NombreEISG" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label asp-for="Precio" class="control-label">Precio </label>
					<input asp-for="Precio" type="number" disabled class="form-control" />
					<span asp-validation-for="Precio" class="text-danger"></span>
				</div>
				<div class="form-group col-md-12">
					<label asp-for="DescripcionEISG" class="control-label"></label>
					<textarea asp-for="DescripcionEISG" disabled class="form-control"></textarea>
					<span asp-validation-for="DescripcionEISG" class="text-danger"></span>
				</div>
				<div class="col-md-6" style="margin-top:10px;">
					<input style="width:100%;" type="submit" value="Eliminar" class="btn btn-danger" />
				</div>
				<div class="col-md-6" style="margin-top:10px;">
					<a style="width:100%;" class="btn btn-secondary" asp-action="Index">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>

EISG20240905.AppWebMVC/Views/ProductEISG/Details.cshtml
@model EISG20240905.DTOs.ProductEISGDTOs.GetIdResultProductEISGDTO

@{
	ViewData["Title"] = "Details";
}
<div class="row" style="margin-top:70px;">
	<div class="row">
		<form asp-action="Details" class="card">
			<div class="card-header row">
				<h1 class="card-text col-md-12">Detalle Producto</h1>
			</div>
			<div class="card-body row">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input asp-for="Id" type="hidden" />
				<div class="form-group col-md-6">
					<label asp-for="NombreEISG" class="control-label">Nombre</label>
					<input asp-for="NombreEISG" disabled class="form-control" />
					<span asp-validation-for="NombreEISG" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label asp-for="Precio" class="control-label">Precio</label>
					<input asp-for="Precio" type="number" disabled class="form-control" />
					<span asp-validation-for="Precio" class="text-danger"></span>
				</div>
				<div class="form-group col-md-12">
					<label asp-for="DescripcionEISG" class="control-label"></label>
					<textarea asp-for="DescripcionEISG" disabled class="form-control"></textarea>
					<span asp-validation-for="DescripcionEISG" class="text-danger"></span>
				</div>
				<div class="col-md-6" style="margin-top:10px;">
					@Html.ActionLink("Modificar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success", style = "width:100%;" })
				</div>
				<div class="col-md-6" style="margin-top:10px;">
					<a class="btn btn-secondary" style="width:100%;" asp-action="Index">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>

EISG20240905.AppWebMVC/Views/ProductEISG/Edit.cshtml
@model EISG20240905.DTOs.ProductEISGDTOs.EditProdcutEISGDTO

@{
	ViewData["Title"] = "Edit";
}

<div class="row" style="margin-top:70px;">
	<div class="row">
		<form asp-action="Edit" class="card">
			<div class="card-header row">
				<h1 class="card-text col-md-12">Modificar Producto</h1>
			</div>
			<div class="card-body row">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input asp-for="Id" type="hidden" />
				<div class="form-group col-md-6">

					<label asp-for="NombreEISG" class="control-label">Nombre<span style="color:red;">*</span></label>
					<input asp-for="NombreEISG" class="form-control" />
					<span asp-validation-for="NombreEISG" class="text-danger"></span>
				</div>
				<div class="form-group col-md-6">
					<label asp-for="Precio" class="control-label">Precio <span style="color:red;">*</span></label>
					<input asp-for="Precio" type="number" class="form-control" />
					<span asp-validation-for="Precio" class="text-danger"></span>
				</div>
				<div class="form-group col-md-12">

					<label asp-for="DescripcionEISG" class="control-label"></label>
					<textarea asp-for="DescripcionEISG" class="form-control"></textarea>
					<span asp-validation-for="DescripcionEISG" class="text-danger"></span>

				</div>
				<div class="form-group col-md-6" style="margin-top:10px;">
					<input type="submit" value="Guardar" class="btn btn-primary" style="width:100%;" />
				</div>
				<div class="col-md-6" style="margin-top:10px;">
					<a class="btn btn-secondary" style="width:100%;" asp-action="Index">Cancelar</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

EISG20240905.AppWebMVC/Views/ProductEISG/Index.cshtml
@model SearchResultProductEISGDTO

@{
    ViewData["Title"] = "Index";
    var modelSearchQuery = ViewBag.SearchQuery as SearchQueryProductEISGDTO;
}

<partial name="SearchQuery" model="modelSearchQuery" />
<partial name="SearchResult" model="Model.Data" />

EISG20240905.AppWebMVC/Views/ProductEISG/SearchQuery.cshtml
@model SearchQueryProductEISGDTO

@{
	// Obtiene el valor de CountRow de la ViewBag
	int totalRegistros = (int)ViewBag.CountRow;
	// Calcula el número total de páginas
	int totalPaginas = (int)Math.Ceiling((double)totalRegistros / Model.Take);
}

<div class="row">
	<div class="row">
		<h1 class="card-text col-md-12">Buscar Productos</h1>
	</div>
	<hr />
	<form asp-action="Index">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<input asp-for="SendRowCount" type="hidden" id="txtSendRowCount" />
		<input asp-for="Skip" type="hidden" id="txtSkip" />
		<input name="CountRow" value="@totalRegistros" type="hidden" />
		<div class="row">
			<div class="form-group col-md-5">

				<label asp-for="NombreEISG_Like" class="control-label"></label>
				<input asp-for="NombreEISG_Like" class="form-control" />
				<span asp-validation-for="NombreEISG_Like" class="text-danger"></span>
			</div>
			<div class="form-group col-md-4">
				<label asp-for="Precio_Like" class="control-label"></label>
				<input type="number" asp-for="Precio_Like" class="form-control" />
				<span asp-validation-for="Precio_Like" class="text-danger"></span>
			</div>
			<div class="form-group col-md-3">
				<label asp-for="Take" class="control-label"></label>
				<select asp-for="Take" class="form-control">
					@for (var i = 10; i < 1000; i += 10)
					{
						if (i == Model.Take)
						{
							<option selected value="@i">@i</option>
						}
						else
						{
							<option value="@i">@i</option>
						}
					}
				</select>
				<span asp-validation-for="Take" class="text-danger"></span>
			</div>
			<div class="form-group col-4" style="margin-top:10px;">
				<input type="submit" id="btnSearch" value="Buscar" style="width:100%;" class="btn btn-secondary" />
			</div>
			<h1 class="card-text col-md-12" style="margin-top:10px;">Lista de Productos</h1>
			<hr />
			<div class="form-group col-4">
				<a asp-action="Create" style="width:100%;" class="btn btn-primary">Registrar</a>
			</div>
			<div class="row" style="margin-top:10px;">
				<nav aria-label="Page navigation example">
					<ul class="pagination">
						@{
							int skipAnte = Model.Skip > 0 ? Model.Skip - Model.Take : 0;
							int skipMax = 0;
						}
						<li class="page-item"><a class="page-link" data-skip="@skipAnte" href="#" onclick="paginacion(this)">Anterior</a></li>
						@for (var i = 0; i < totalPaginas; i++)
						{
							int skip = i * Model.Take;
							int numPag = i + 1;
							if (skip != Model.Skip)
							{
								<li class="page-item"><a class="page-link" data-skip="@skip" href="#" onclick="paginacion(this)">@numPag</a></li>
							}
							else
							{
								<li class="page-item active"><a class="page-link" data-skip="@skip" href="#" onclick="paginacion(this)">@numPag</a></li>
							}
							skipMax = skip;
						}
						@{
							int skipSi = Model.Skip + Model.Take;
							skipSi = skipSi > skipMax ? skipSi - Model.Take : skipSi;
						}
						<li class="page-item"><a class="page-link" data-skip="@skipSi" href="#" onclick="paginacion(this)">Siguiente</a></li>
					</ul>
				</nav>
			</div>
			<div class="row">
				<div class="col-md-6">
					<span class="fw-bold">Total registros: <span class="badge bg-primary">@totalRegistros</span></span>
				</div>
			</div>
		</div>








	</form>




</div>
<script>
	function paginacion(li) {
		const skip = li.getAttribute("data-skip");
		const btnSearch = document.getElementById("btnSearch");
		const txtSkip = document.getElementById("txtSkip");
		const txtSendRowCount = document.getElementById("txtSendRowCount");
		txtSkip.value = skip;
		txtSendRowCount.value = 1;
		btnSearch.click();
	}
</script>

EISG20240905.AppWebMVC/Views/ProductEISG/SearchResult.cshtml
@model IEnumerable<SearchResultProductEISGDTO.ProductEISGDTO>
<div class="row" style="margin-top:10px;">
	<div class="table-responsive col-md-12">
		<table class="table table-striped table-hover table-secondary">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(item => item.NombreEISG)
					</th>
					<th>
						@Html.DisplayNameFor(item => item.DescripcionEISG)
					</th>
					<th>
						@Html.DisplayNameFor(item => item.Precio)
					</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.NombreEISG)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.DescripcionEISG)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Precio)
						</td>
						<td>
							<table>
								<td>
									@Html.ActionLink("Modificar", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })

								</td>
								<td>
									@Html.ActionLink("Detalle", "Details", new { id = item.Id }, new { @class = "btn btn-info" })

								</td>
								<td>
									@Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })

								</td>
							</table>

						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

EISG20240905.AppWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EISG20240905.AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EISG20240905.AppWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EISG20240905.AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductEISG" asp-action="Index">Productos</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EISG20240905.AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>